services:
    realchill-test:
        image: itzg/minecraft-server
        container_name: realchill-test
        tty: true
        stdin_open: true
        ports:
            - '25565:25565'
            - '25566:25566'
            - '25567:25567'
            - '24454:24454/udp'
        restart: unless-stopped
        environment:
            EULA: 'TRUE'
            MAX_MEMORY: 8G
            TYPE: FORGE
            VERSION: '1.20.1'
            FORGE_VERSION: '47.4.3'
            PACKWIZ_URL: '/modpack/pack.toml'
            FORCE_REDOWNLOAD: 'true'

            ONLINE_MODE: 'TRUE'
            ENABLE_COMMAND_BLOCK: 'TRUE'

            OPS: |
                ThatDraenGuy
        volumes:
            - ./server-data:/data
            - .:/modpack
