name = "Realchill"
author = "ThatDraenGuy"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3019b0c340e0f642551ec0dc546f990c73c283f664c974facb28a8a455a49da3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
