name = "Realchill"
author = "ThatDraenGuy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad1084bedf3454c9380b24c23b1d3dd557e4172a37f570cb523a565db193d3c4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
