name = "Realchill"
author = "ThatDraenGuy"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14f1865bbe55cf60edd4c975a595f6dc1b40b8a07fcd027b15f00a91685cb776"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
