name = "Realchill"
author = "ThatDraenGuy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d897269a2291aec2e24b06005c60faac568ce596075ca1af43252e6b46e7efc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
