name = "Realchill"
author = "ThatDraenGuy"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93d28834b461424ca84ad61addb7fad4c98390ed04ee7d202d5deaef0040cbaa"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
