name = "Realchill"
author = "ThatDraenGuy"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bc6cc9db78bfcc53123c1980a82b4978d558d8cbcab432c3bdf4d8e9d5e6beb"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
