name = "Realchill"
author = "ThatDraenGuy"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b622ef212458ca69cfd57a6d0eee716840aa05022aea84c67358c2b9748f6cb1"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
