name = "Realchill"
author = "ThatDraenGuy"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bda7ae447b8f85e08002d59763a3c16fb8f7155cc4f4a1ea5168642158b0f82"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
