name = "Realchill"
author = "ThatDraenGuy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95604d0abbd029da91144c95e48dc54a6d001b0312ef6d4b2d0fb886b32e731c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
