name = "Realchill"
author = "ThatDraenGuy"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9790b894f86b61b17fb33ab672526d35b48c7e7325bf1422312af1b286dcde01"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
