name = "Realchill"
author = "ThatDraenGuy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2068426bf421308fd43c6be87ed6c757506fceccebdb436193a5569094696f9f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
