name = "Realchill"
author = "ThatDraenGuy"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a975b3c54bbc7b69b7a9a9e99b775933e3cf9c52ccfc9bfe33eb4c3cfb40789"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
