name = "Realchill"
author = "ThatDraenGuy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7af2b183735b2ac3b0c29e5392beda0615ebecc6a605459f8428c752ea816c3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
