name = "Realchill"
author = "ThatDraenGuy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e60b6804f480ebf0210302d15d24c9b235ced36bc3ac5b69dfea7966a49b6c8f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
