name: publish

on:
    push:
        tags:
            - '*'
        branches: ['main']

env:
    MODPACK_NAME: Realchill

jobs:
    publish-archive:
        name: publish modpack archive
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install java
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - name: Prepare packwiz
              run: |
                  mkdir client
                  mkdir both
                  mkdir server
                  curl -L --output packwiz-installer-bootstrap.jar  "https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar"
            - name: Build client
              run: |
                  cd client
                  java -jar ../packwiz-installer-bootstrap.jar --no-gui -s client ../pack.toml
                  zip -r ${{ env.MODPACK_NAME }}-${{ github.ref_name }}-client.zip *
                  cd ..
            - name: Build full
              run: |
                  cd full
                  java -jar ../packwiz-installer-bootstrap.jar --no-gui -s both ../pack.toml
                  zip -r ${{ env.MODPACK_NAME }}-${{ github.ref_name }}-full.zip *
                  cd ..
            - name: Build server
              run: |
                  cd server
                  java -jar ../packwiz-installer-bootstrap.jar --no-gui -s server ../pack.toml
                  zip -r ${{ env.MODPACK_NAME }}-${{ github.ref_name }}-server.zip *
                  cd ..

            - name: Release with Notes
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      client/${{ env.MODPACK_NAME }}-${{ github.ref_name }}-client.zip
                      full/${{ env.MODPACK_NAME }}-${{ github.ref_name }}-full.zip
                      server/${{ env.MODPACK_NAME }}-${{ github.ref_name }}-server.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish-packwiz-files:
        name: publish packwiz files
        runs-on: ubuntu-latest
        environment: packwiz-file-host

        steps:
            - name: install ssh keys
              run: |
                  install -m 600 -D /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            - name: connect and pull
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull && exit"
            - name: cleanup
              run: rm -rf ~/.ssh
